dist: trusty
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
script:
  - export CC=gcc-7
  - export CXX=g++-7
  - cmake -H. -Bbuild
  - cmake --build build
  - ./build/unit_tests
  - ./build/threading_examples

