#include <omp.h>
#include <iostream>                                                             
#include <fstream>    
#include <ctime>
#include <numeric>
#include <vector>
#include <string>
#include <math.h>
#include <sstream>
#include <set>
#include <sys/time.h>
#include <complex>
#include <cstdlib>
#include <functional>
#include <iomanip>
#include <random>
#include <queue>
#include <stack> 
#include <climits>
#include <thread>
#include <mutex>
#include <condition_variable>
using namespace std;
